- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
  tasks:
      - import_tasks: tasks/ssh.yml
      - import_tasks: tasks/zsh-setup.yml
      - import_tasks: tasks/core-setup.yml
    #      - import_tasks: tasks/dotfiles.yml
      - import_tasks: tasks/dotfiles-wsl.yml
      - import_tasks: tasks/nvim-setup.yml
#      - import_tasks: tasks/git-setup.yml
#      - import_tasks: tasks/signal-setup.yml
      - import_tasks: tasks/node-setup.yml
