- name: Install System Packages 1 (ninja-build gettext cmake unzip curl)

  become: true
  apt:
    name: ["ninja-build", "gettext", "cmake", "unzip", "curl"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 (i3, tmux, flameshot, stow, fzf, tldr, ripgrep, gimp, python3, python3-pip)

  become: true
  apt:
    name: ["i3", "tmux", "flameshot", "stow", "fzf", "tldr", "xclip", "ripgrep", "gimp", "python3", "python3-pip"]
  tags:
    - install
    - core
