- name: Remove neovim
  shell: rm -rf ~/neovim
  tags:
    - install
    - neovim

- name: Clone Neovim Stable Branch
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    version: "stable"
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - install
    - neovim

- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo
  tags:
    - install
    - neovim

- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && cd build && cpack -G DEB && sudo dpkg -i nvim-linux64.deb
  tags:
    - install
    - neovim
